### ISSUE TITLE
npd-rule.yaml is missing

### ISSUE THREAD

**Issue by yunkunrao** [kubesphere/kubeye#27]
When execute `ke install npd`，cli prompt "Failed to get npd-rule.yaml: stat /root/kubeye/examples/npd-rule.yaml: no such file or directory". And npd-rule.yaml was not found in repo example folder.

**Comment by Forest-L** [comment]
ok, let's see

**Comment by Forest-L** [comment]
https://github.com/kubesphere/kubeye/pull/28
Fixed it. You can compile or download the latest binary package.

**Comment by yunkunrao** [comment]
Thanks, this issue was fixed now.
