### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubeye#31]
Comment on Issue or Pull Request, asking @all-contributors to add a contributor:

`@all-contributors please add @<username> for <contributions>`

**Comment by pixiake** [comment]
@all-contributors please add @Forest-L  for code,doc

**Comment by pixiake** [comment]
@all-contributors please add @Forest-L for code, doc

**Comment by pixiake** [comment]
@all-contributors please add @zryfish  for  doc

**Comment by pixiake** [comment]
@all-contributors please add @shaowenchen  for code

**Comment by shaowenchen** [comment]
@all-contributors

**Comment by shaowenchen** [comment]
@all-contributors please add @shaowenchen for code

**Comment by pixiake** [comment]
@all-contributors please add @pixiake  for doc

**Comment by pixiake** [comment]
@all-contributors please add @pixiake  for doc
